// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANP9-ysDcLoGcG649qb7kjr1ndnoo_blk',
    appId: '1:286864398213:web:5eb2b6f183ac5a7db156ec',
    messagingSenderId: '286864398213',
    projectId: 'chat-app-eaed7',
    authDomain: 'chat-app-eaed7.firebaseapp.com',
    storageBucket: 'chat-app-eaed7.firebasestorage.app',
    measurementId: 'G-40N7ZT3EED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSEcibBEPhJufQuveZHYbCNolkdgyeywk',
    appId: '1:286864398213:android:6e1681fe4956fffcb156ec',
    messagingSenderId: '286864398213',
    projectId: 'chat-app-eaed7',
    storageBucket: 'chat-app-eaed7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbQrCgquISQJa2yPNYWlIx6FIlqq4dHoo',
    appId: '1:286864398213:ios:194cfa1d3b32f168b156ec',
    messagingSenderId: '286864398213',
    projectId: 'chat-app-eaed7',
    storageBucket: 'chat-app-eaed7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbQrCgquISQJa2yPNYWlIx6FIlqq4dHoo',
    appId: '1:286864398213:ios:194cfa1d3b32f168b156ec',
    messagingSenderId: '286864398213',
    projectId: 'chat-app-eaed7',
    storageBucket: 'chat-app-eaed7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANP9-ysDcLoGcG649qb7kjr1ndnoo_blk',
    appId: '1:286864398213:web:41db68d30f9880f1b156ec',
    messagingSenderId: '286864398213',
    projectId: 'chat-app-eaed7',
    authDomain: 'chat-app-eaed7.firebaseapp.com',
    storageBucket: 'chat-app-eaed7.firebasestorage.app',
    measurementId: 'G-GXWKX21D9Z',
  );
}
